"""English symptom-language vocabulary aligned with ``symptom_vocab``.

Each English entry list is the set of strings to substring-match in
English text in order to flag the same TCM symptom category as the
Chinese counterpart at the same dict key in ``SYMPTOM_GROUPS``.

Used by Task 11 (corpus filtering on the English PubMed corpus) and
Task 20 (held-out symptom probe) when the underlying corpus is
English-language. The ZH and EN tables share keys (e.g. ``thermal``)
so any consumer can ask for both via a language switch.

Coverage rule of thumb: each Chinese term gets 2-4 likely English
phrasings (clinical + lay vocabulary). Substring matches use
case-insensitive `in` semantics — keep entries lowercase and prefer
multi-word phrases over single words to limit false positives
(e.g. ``"feels cold"`` not ``"cold"``).
"""

from __future__ import annotations

SYMPTOM_GROUPS_EN: dict[str, list[str]] = {
    "thermal": [
        "cold intolerance",
        "feels cold",
        "feeling cold",
        "aversion to cold",
        "cold extremities",
        "cold limbs",
        "cold hands",
        "cold feet",
        "low-grade fever",
        "tidal fever",
        "afternoon fever",
        "feverish",
        "hot flashes",
        "hot flush",
        "hot flushes",
        "thirst",
        "thirsty",
        "dry mouth",
        "dry throat",
        "night sweat",
        "night sweats",
        "spontaneous sweating",
        "flushed face",
        "red face",
    ],
    "energy": [
        "fatigue",
        "fatigued",
        "exhausted",
        "weakness",
        "weariness",
        "lack of energy",
        "lethargy",
        "lethargic",
        "shortness of breath",
        "reluctant to speak",
        "lassitude",
        "low spirits",
        "drowsiness",
        "drowsy",
        "somnolence",
        "insomnia",
        "sleeplessness",
        "trouble sleeping",
        "vivid dreams",
        "excessive dreaming",
        "many dreams",
    ],
    "digestive": [
        "abdominal distension",
        "abdominal bloating",
        "bloated abdomen",
        "abdominal pain",
        "stomach pain",
        "stomachache",
        "poor appetite",
        "loss of appetite",
        "anorexia",
        "nausea",
        "nauseated",
        "vomiting",
        "emesis",
        "loose stool",
        "loose stools",
        "soft stools",
        "constipation",
        "constipated",
        "diarrhea",
        "diarrhoea",
        "belching",
        "burping",
        "eructation",
        "acid reflux",
        "acid regurgitation",
        "heartburn",
        "epigastric pain",
        "stomach distension",
        "bitter taste in mouth",
        "bad breath",
        "halitosis",
    ],
    "respiratory": [
        "cough",
        "coughing",
        "wheezing",
        "wheeze",
        "asthma",
        "panting",
        "rapid breathing",
        "phlegm",
        "sputum",
        "excessive phlegm",
        "chest tightness",
        "tight chest",
        "chest pain",
        "nasal congestion",
        "stuffy nose",
        "blocked nose",
        "runny nose",
        "rhinorrhea",
        "rhinorrhoea",
        "itchy throat",
        "throat itch",
        "hoarseness",
        "hoarse voice",
    ],
    "head_sensory": [
        "headache",
        "head pain",
        "migraine",
        "dizziness",
        "dizzy",
        "vertigo",
        "lightheaded",
        "blurred vision",
        "visual disturbance",
        "tinnitus",
        "ringing in the ears",
        "red eyes",
        "bloodshot eyes",
        "sore throat",
        "throat pain",
        "dry eyes",
        "hearing loss",
        "deafness",
    ],
    "musculoskeletal": [
        "low back pain",
        "lumbar pain",
        "lower back pain",
        "joint pain",
        "arthralgia",
        "muscle aches",
        "muscle soreness",
        "body aches",
        "numbness",
        "tingling",
        "paresthesia",
        "muscle cramps",
        "cramping",
        "weak knees",
        "weak lower back",
        "shoulder pain",
    ],
    "psychoaffective": [
        "palpitations",
        "palpitation",
        "heart palpitation",
        "anxiety",
        "anxious",
        "restlessness",
        "irritability",
        "irritable",
        "easily angered",
        "depression",
        "depressed mood",
        "low mood",
        "sadness",
        "sad",
        "fear",
        "fearfulness",
        "forgetfulness",
        "poor memory",
        "memory loss",
        "vexation",
        "agitation",
    ],
    "urogenital": [
        "frequent urination",
        "urinary frequency",
        "urgent urination",
        "urinary urgency",
        "difficulty urinating",
        "dysuria",
        "urinary retention",
        "nocturia",
        "frequent night urination",
        "nocturnal emission",
        "spermatorrhea",
        "impotence",
        "erectile dysfunction",
        "irregular menstruation",
        "menstrual irregularity",
        "dysmenorrhea",
        "painful menstruation",
        "menstrual pain",
        "leukorrhea",
        "vaginal discharge",
    ],
    "skin_circulation": [
        "itching",
        "pruritus",
        "itchy skin",
        "skin rash",
        "rash",
        "swelling",
        "edema",
        "oedema",
        "bruising",
        "ecchymosis",
        "rough skin",
        "scaly skin",
        "pale complexion",
        "pallor",
        "sallow complexion",
        "yellowish complexion",
    ],
}


def all_terms_en() -> list[str]:
    """Flat dedup list of English symptom phrasings across all groups."""
    seen: set[str] = set()
    out: list[str] = []
    for group in SYMPTOM_GROUPS_EN.values():
        for term in group:
            if term not in seen:
                seen.add(term)
                out.append(term)
    return out


SYMPTOM_TERMS_EN: list[str] = all_terms_en()
